# Generated by Django 6.0.2 on 2026-03-22 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thesis', models.TextField()),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('RU', 'Running'), ('CP', 'Completed'), ('FD', 'Failed')], default='PD', max_length=2)),
                ('final_report', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_data', models.JSONField(default=dict)),
                ('tool_history', models.JSONField(default=dict)),
                ('iteration_count', models.IntegerField(default=0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research.researchreport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(max_length=20)),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField()),
                ('execution_time', models.TimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
